name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-26, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ runner.os == 'Windows' }}
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - if: ${{ runner.os == 'macOS' }}
        run: brew install libomp
      - run: bundle exec rake vendor:platform
      - run: bundle exec rake test
